// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package valhalla

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson727fe99aDecodeGithubComLittlemonkeyltdValhallaGoBindings(in *jlexer.Lexer, out *StatusResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "version":
			out.Version = string(in.String())
		case "tileset_last_modified":
			out.TileSetLastModified = int(in.Int())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson727fe99aEncodeGithubComLittlemonkeyltdValhallaGoBindings(out *jwriter.Writer, in StatusResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"version\":"
		out.RawString(prefix[1:])
		out.String(string(in.Version))
	}
	{
		const prefix string = ",\"tileset_last_modified\":"
		out.RawString(prefix)
		out.Int(int(in.TileSetLastModified))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v StatusResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson727fe99aEncodeGithubComLittlemonkeyltdValhallaGoBindings(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v StatusResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson727fe99aEncodeGithubComLittlemonkeyltdValhallaGoBindings(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *StatusResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson727fe99aDecodeGithubComLittlemonkeyltdValhallaGoBindings(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *StatusResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson727fe99aDecodeGithubComLittlemonkeyltdValhallaGoBindings(l, v)
}
